name = "Better Than Employment"
author = "Fripe"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "685811ada74bb4f816d6ffd5830cf411ddec482708a74fc0469944a92ce0a2c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
