name = "Better Than Employment"
author = "Fripe"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d539d255c675582148c70398454c3eca9ba8d10e82a0b2457c7a4bd512645f3e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
