name = "Better Than Employment"
author = "Fripe"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e275e5825a9bf4e872aedbdab0e7a68d9c29e49adc1e1ab2f3acce10c459c15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
