---
name: packwiz deploy

on:
  release:
    types: [published]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Packwiz refresh
        run: packwiz refresh --build --pack-file pack/pack.toml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: pack/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
